version: '3.8'

services:
  fast_api:
    image: fast_api
    container_name: fast_api
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    volumes:
      - .:/fast_api:z
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.fastapi
      - ./.envs/.mongo
    depends_on:
      - mongo
    command: /start

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - ./.envs/.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    container_name: mongo-admin
    image: mongo-express
    restart: unless-stopped
    ports:
        - "8081:8081"
    env_file:
      - ./.envs/.mongo
    depends_on:
      - mongo

volumes:
  mongo_data:
