version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.fastapi
    depends_on:
      - db

  mongo:
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - ./.envs/.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
        - "8081:8081"
    env_file:
      - ./.envs/.mongo
    depends_on:
      - mongo

volumes:
  mongo_data:
