services:
  fast_api:
    image: fast_api
    container_name: fast_api
    build:
      context: .
      dockerfile: compose/fastapi/Dockerfile
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.fastapi
      - .envs/.mysql
    depends_on:
      - mysql
    command: /start
    ports:
      - "8000:8000"

  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./compose/mysql/Dockerfile
    restart: always
    env_file:
      - ./.envs/.mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_data_backups:/backups
      - ./compose/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    env_file:
      - .envs/.mysql
    volumes:
      - /sessions
    ports:
      - "8080:80"

volumes:
    mysql_data: {}
    mysql_data_backups: {}