#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -z "${MONGO_INITDB_ROOT_USERNAME}" ]; then
    base_mongo_image_default_user="root"
    export MONGO_INITDB_ROOT_USERNAME="${base_mongo_image_default_user}"
fi
export DATABASE_URL="mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin"

python << END
import sys
import time
import motor

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        client = pymongo.AsyncMongoClient(DATABASE_URL)
        client.admin.command("ping")
        break
    except pymongo.errors.ConnectionFailure as error:
        sys.stderr.write("Waiting for MongoDB to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))
    time.sleep(1)
END

>&2 echo "MongoDB is available"

exec "$@"